const CONFIG_KEY='randerscrm_cloud_config_v1';
const SESSION_KEY='randerscrm_cloud_session_v1';
export const loadCloudConfig=()=>{try{return JSON.parse(localStorage.getItem(CONFIG_KEY))||{url:'',anonKey:''}}catch{return{url:'',anonKey:''}}};
export const saveCloudConfig=c=>localStorage.setItem(CONFIG_KEY,JSON.stringify(c));
export const loadCloudSession=()=>{try{return JSON.parse(sessionStorage.getItem(SESSION_KEY))}catch{return null}};
const saveSession=s=>s?sessionStorage.setItem(SESSION_KEY,JSON.stringify(s)):sessionStorage.removeItem(SESSION_KEY);
const headers=(config,token,extra={})=>({'apikey':config.anonKey,'Authorization':`Bearer ${token||config.anonKey}`,'Content-Type':'application/json',...extra});
const request=async(config,path,options={})=>{if(!config.url||!config.anonKey)throw new Error('Informe a URL e a chave pública anon do Supabase.');const res=await fetch(`${config.url.replace(/\/$/,'')}${path}`,options);let body=null;try{body=await res.json()}catch{}if(!res.ok)throw new Error(body?.msg||body?.message||body?.error_description||body?.hint||`Falha HTTP ${res.status}`);return body};
const auth=(config,session,extra={})=>headers(config,session?.access_token,extra);
export async function testConnection(config){await request(config,'/rest/v1/',{headers:headers(config)});return true}
export async function signInCloud(config,email,password){const data=await request(config,'/auth/v1/token?grant_type=password',{method:'POST',headers:headers(config),body:JSON.stringify({email,password})});const session={access_token:data.access_token,refresh_token:data.refresh_token,user:data.user,expires_at:Date.now()+((data.expires_in||3600)*1000)};saveSession(session);return session}
export async function signOutCloud(config,session){if(session?.access_token){try{await request(config,'/auth/v1/logout',{method:'POST',headers:headers(config,session.access_token)})}catch{}}saveSession(null)}
export async function pushSnapshot(config,session,state){if(!session?.access_token)throw new Error('Autentique uma conta do Supabase primeiro.');const payload={user_id:session.user.id,payload:state,updated_at:new Date().toISOString()};await request(config,'/rest/v1/crm_snapshots?on_conflict=user_id',{method:'POST',headers:auth(config,session,{Prefer:'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify(payload)});return payload.updated_at}
export async function pullSnapshot(config,session){if(!session?.access_token)throw new Error('Autentique uma conta do Supabase primeiro.');const rows=await request(config,`/rest/v1/crm_snapshots?user_id=eq.${encodeURIComponent(session.user.id)}&select=payload,updated_at&limit=1`,{headers:auth(config,session)});return rows?.[0]||null}
const clean=v=>v===undefined?null:v;
const rowsFor=(state,owner)=>({
 crm_users:(state.users||[]).map(u=>({owner_id:owner,local_id:String(u.id),nome:u.nome,email:u.email,cargo:u.cargo,carteira:u.carteira,ativo:u.ativo!==false,avatar_config:u.avatarConfig||{},updated_at:new Date().toISOString()})),
 crm_revendedores:(state.revendedores||[]).map(r=>({owner_id:owner,local_id:String(r.id),codigo:clean(r.codigo),nome:r.nome||'Sem nome',telefone:clean(r.telefone),cidade:clean(r.cidade),bairro:clean(r.bairro),nivel:clean(r.nivel),base:clean(r.base),atividade:clean(r.atividade),status:r.status||'Pendente',responsavel:clean(r.responsavel),metadata:r.metadata||{},updated_at:new Date().toISOString()})),
 crm_atendimentos:(state.history||[]).map(h=>({owner_id:owner,local_id:String(h.id),revendedor_local_id:String(h.revendedorId),usuario:clean(h.usuario),canal:h.canal||'Outro',resultado:h.resultado||'Registrado',observacao:clean(h.observacao),occurred_at:h.data||new Date().toISOString(),updated_at:new Date().toISOString()})),
 crm_agenda:(state.agenda||[]).map(a=>({owner_id:owner,local_id:String(a.id),revendedor_local_id:String(a.revendedorId),responsavel:clean(a.responsavel),data:a.data,hora:clean(a.hora),status:a.status||'Pendente',observacao:clean(a.observacao),updated_at:new Date().toISOString()})),
 crm_metas:Object.entries(state.goals||{}).map(([id,g])=>({owner_id:owner,user_local_id:String(id),calls:Number(g.calls||0),whats:Number(g.whats||0),conversions:Number(g.conversions||0),updated_at:new Date().toISOString()})),
 crm_campanhas:(state.campaigns||[]).map(c=>({owner_id:owner,local_id:String(c.id),payload:c,updated_at:new Date().toISOString()})),
 crm_auditoria:(state.audit||[]).map(a=>({owner_id:owner,local_id:String(a.id),usuario:clean(a.user),acao:a.action||'Ação',occurred_at:a.date||new Date().toISOString()})),
 crm_importacoes:(state.imports||[]).map(i=>({owner_id:owner,local_id:String(i.id||crypto.randomUUID()),payload:i,updated_at:new Date().toISOString()}))
});
const upsert=async(config,session,table,rows,conflict='owner_id,local_id')=>{if(!rows.length)return 0;const chunk=300;for(let i=0;i<rows.length;i+=chunk){await request(config,`/rest/v1/${table}?on_conflict=${encodeURIComponent(conflict)}`,{method:'POST',headers:auth(config,session,{Prefer:'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify(rows.slice(i,i+chunk))})}return rows.length};
export async function pushNormalized(config,session,state,onProgress=()=>{}){if(!session?.access_token)throw new Error('Autentique uma conta do Supabase primeiro.');const all=rowsFor(state,session.user.id);let total=0;for(const [table,rows] of Object.entries(all)){onProgress(`Enviando ${table.replace('crm_','')}...`);total+=await upsert(config,session,table,rows,table==='crm_metas'?'owner_id,user_local_id':'owner_id,local_id')}const when=new Date().toISOString();return{when,total,counts:Object.fromEntries(Object.entries(all).map(([k,v])=>[k,v.length]))}}
const selectAll=async(config,session,table)=>request(config,`/rest/v1/${table}?owner_id=eq.${encodeURIComponent(session.user.id)}&select=*`,{headers:auth(config,session)});
export async function pullNormalized(config,session,onProgress=()=>{}){if(!session?.access_token)throw new Error('Autentique uma conta do Supabase primeiro.');const tables=['crm_users','crm_revendedores','crm_atendimentos','crm_agenda','crm_metas','crm_campanhas','crm_auditoria','crm_importacoes'];const data={};for(const t of tables){onProgress(`Baixando ${t.replace('crm_','')}...`);data[t]=await selectAll(config,session,t)}return{
 users:data.crm_users.map(u=>({id:u.local_id,nome:u.nome,email:u.email,senha:'',cargo:u.cargo,carteira:u.carteira,ativo:u.ativo,avatarConfig:u.avatar_config||{}})),
 revendedores:data.crm_revendedores.map(r=>({id:r.local_id,codigo:r.codigo,nome:r.nome,telefone:r.telefone,cidade:r.cidade,bairro:r.bairro,nivel:r.nivel,base:r.base,atividade:r.atividade,status:r.status,responsavel:r.responsavel,metadata:r.metadata||{}})),
 history:data.crm_atendimentos.map(h=>({id:h.local_id,revendedorId:h.revendedor_local_id,usuario:h.usuario,canal:h.canal,resultado:h.resultado,observacao:h.observacao,data:h.occurred_at})),
 agenda:data.crm_agenda.map(a=>({id:a.local_id,revendedorId:a.revendedor_local_id,responsavel:a.responsavel,data:a.data,hora:a.hora,status:a.status,observacao:a.observacao})),
 goals:Object.fromEntries(data.crm_metas.map(m=>[m.user_local_id,{calls:m.calls,whats:m.whats,conversions:m.conversions}])),
 campaigns:data.crm_campanhas.map(c=>c.payload),audit:data.crm_auditoria.map(a=>({id:a.local_id,user:a.usuario,action:a.acao,date:a.occurred_at})),imports:data.crm_importacoes.map(i=>i.payload)
}}
