import React,{useMemo,useState} from 'react';
import {RefreshCw,UserPlus,Users} from 'lucide-react';
import AvatarPreview from './AvatarPreview';
import{defaultAvatar}from'../data/avatarOptions';
import{assignmentSummary}from'../services/assignment';
const wallets=['Recuperação','Cobre a Ouro','VIP','Todas'];
const roles=['Consultor','Gerente','Administrador'];
export default function Admin({users,revendedores=[],onInvite,onUpdate,onDistribute,loading=false}){
 const [form,setForm]=useState({nome:'',email:'',cargo:'Consultor',carteira:'Recuperação'}),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');
 const summary=useMemo(()=>assignmentSummary(revendedores,users),[revendedores,users]);
 const submit=async e=>{e.preventDefault();setError('');if(!form.nome.trim()||!form.email.trim())return setError('Informe nome e e-mail.');setSubmitting(true);try{await onInvite(form);setForm({nome:'',email:'',cargo:'Consultor',carteira:'Recuperação'})}catch(err){setError(err.message||'Não foi possível enviar o convite.')}finally{setSubmitting(false)}};
 return <section className="module-page"><div className="admin-grid"><form className="panel form-panel" onSubmit={submit}><div className="panel-title"><div><small>Convite por e-mail</small><h2>Novo colaborador</h2></div><UserPlus size={20}/></div><label>Nome completo<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} placeholder="Nome do colaborador"/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="colaborador@empresa.com"/></label><div className="form-row"><label>Cargo<select value={form.cargo} onChange={e=>setForm({...form,cargo:e.target.value})}>{roles.map(role=><option key={role}>{role}</option>)}</select></label><label>Carteira<select value={form.carteira} onChange={e=>setForm({...form,carteira:e.target.value})}>{wallets.map(w=><option key={w}>{w}</option>)}</select></label></div>{error&&<div className="form-error">{error}</div>}<button className="primary" disabled={submitting}>{submitting?'Enviando convite...':'Enviar convite de acesso'}</button><p className="form-help">O colaborador receberá um e-mail do Supabase para confirmar a conta e definir o primeiro acesso.</p></form><article className="panel"><div className="panel-title"><div><small>Equipe real no Supabase</small><h2>Usuários e carteiras</h2></div><span>{users.length}</span></div>{loading?<div className="empty-state">Carregando colaboradores...</div>:<div className="user-list">{users.map(u=><div className="user-row" key={u.id}><span className="user-avatar"><AvatarPreview compact avatar={u.avatarConfig||defaultAvatar}/></span><div className="user-details"><b>{u.nome}</b><small>{u.email||'E-mail pendente'} · {u.emailConfirmed?'Confirmado':'Aguardando confirmação'}</small></div><select value={u.cargo} onChange={e=>onUpdate(u.id,{cargo:e.target.value})}>{roles.map(role=><option key={role}>{role}</option>)}</select><select value={u.carteira} onChange={e=>onUpdate(u.id,{carteira:e.target.value})}>{wallets.map(w=><option key={w}>{w}</option>)}</select><label className="switch"><input type="checkbox" checked={u.ativo} onChange={e=>onUpdate(u.id,{ativo:e.target.checked})}/><span>{u.ativo?'Ativo':'Inativo'}</span></label></div>)}</div>}</article></div><article className="panel assignment-panel"><div className="panel-title"><div><small>Distribuição automática</small><h2>Carteiras dos consultores</h2><p>Contatos são divididos entre os colaboradores ativos do mesmo grupo, sem duplicidade.</p></div><button className="primary" onClick={onDistribute}><RefreshCw size={17}/>Redistribuir agora</button></div><div className="assignment-summary">{summary.map(item=><div key={item.id}><span className="assignment-avatar"><Users size={18}/></span><div><b>{item.nome}</b><small>{item.carteira}</small></div><strong>{item.total}</strong><span>revendedores</span></div>)}</div></article></section>
}
