import React,{useMemo,useState} from 'react';
import {RefreshCw,UserPlus,Users} from 'lucide-react';
import AvatarPreview from './AvatarPreview';
import{defaultAvatar}from'../data/avatarOptions';
import{assignmentSummary}from'../services/assignment';
const wallets=['Sem carteira','Recuperação','Cobre a Ouro','VIP','Todas'];
export default function Admin({users,revendedores=[],onAdd,onUpdate,onDistribute}){
 const [form,setForm]=useState({nome:'',email:'',senha:'',cargo:'Consultor',carteira:'Sem carteira',avatarConfig:defaultAvatar});
 const summary=useMemo(()=>assignmentSummary(revendedores,users),[revendedores,users]);
 const submit=e=>{e.preventDefault();if(!form.nome||!form.email||!form.senha)return;onAdd({...form,id:crypto.randomUUID(),ativo:true});setForm({nome:'',email:'',senha:'',cargo:'Consultor',carteira:'Sem carteira',avatarConfig:defaultAvatar})};
 return <section className="module-page"><div className="admin-grid"><form className="panel form-panel" onSubmit={submit}><div className="panel-title"><h2>Novo colaborador</h2><UserPlus size={20}/></div><label>Nome<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Senha<input type="password" value={form.senha} onChange={e=>setForm({...form,senha:e.target.value})}/></label><div className="form-row"><label>Cargo<select value={form.cargo} onChange={e=>setForm({...form,cargo:e.target.value})}><option>Consultor</option><option>Gerente</option><option>Administrador</option></select></label><label>Carteira<select value={form.carteira} onChange={e=>setForm({...form,carteira:e.target.value})}>{wallets.map(w=><option key={w}>{w}</option>)}</select></label></div><button className="primary">Cadastrar colaborador</button></form><article className="panel"><div className="panel-title"><h2>Usuários e carteiras</h2><span>{users.length}</span></div><div className="user-list">{users.map(u=><div className="user-row" key={u.id}><span className="user-avatar"><AvatarPreview compact avatar={u.avatarConfig}/></span><div><b>{u.nome}</b><small>{u.email} · {u.cargo}</small></div><select value={u.carteira} onChange={e=>onUpdate(u.id,{carteira:e.target.value})}>{wallets.map(w=><option key={w}>{w}</option>)}</select><label className="switch"><input type="checkbox" checked={u.ativo} onChange={e=>onUpdate(u.id,{ativo:e.target.checked})}/><span>{u.ativo?'Ativo':'Inativo'}</span></label></div>)}</div></article></div><article className="panel assignment-panel"><div className="panel-title"><div><small>Distribuição automática</small><h2>Carteiras dos consultores</h2><p>O mesmo contato nunca aparece para dois colaboradores do mesmo grupo.</p></div><button className="primary" onClick={onDistribute}><RefreshCw size={17}/>Redistribuir agora</button></div><div className="assignment-summary">{summary.map(item=><div key={item.id}><span className="assignment-avatar"><Users size={18}/></span><div><b>{item.nome}</b><small>{item.carteira}</small></div><strong>{item.total}</strong><span>revendedores</span></div>)}</div></article></section>
}
