import React,{useMemo,useState} from 'react';
import {CalendarPlus,CheckCircle2,MessageCircle} from 'lucide-react';
export default function Agenda({agenda,revendedores,user,onAdd,onUpdate}){
 const [form,setForm]=useState({revendedorId:'',data:new Date().toISOString().slice(0,10),hora:'09:00',observacao:''});
 const visible=useMemo(()=>agenda.filter(a=>user.cargo==='Administrador'||a.responsavel===user.nome).sort((a,b)=>`${a.data}${a.hora}`.localeCompare(`${b.data}${b.hora}`)),[agenda,user]);
 const submit=e=>{e.preventDefault();if(!form.revendedorId)return;onAdd({...form,id:crypto.randomUUID(),responsavel:user.nome,status:'Pendente'});setForm({...form,revendedorId:'',observacao:''})};
 const name=id=>revendedores.find(r=>r.id===id)?.nome||'Revendedor removido';
 return <section className="module-page"><div className="agenda-grid"><form className="panel form-panel" onSubmit={submit}><div className="panel-title"><h2>Novo retorno</h2><CalendarPlus size={20}/></div><label>Revendedor<select value={form.revendedorId} onChange={e=>setForm({...form,revendedorId:e.target.value})}><option value="">Selecione</option>{revendedores.map(r=><option key={r.id} value={r.id}>{r.nome}</option>)}</select></label><div className="form-row"><label>Data<input type="date" value={form.data} onChange={e=>setForm({...form,data:e.target.value})}/></label><label>Hora<input type="time" value={form.hora} onChange={e=>setForm({...form,hora:e.target.value})}/></label></div><label>Observação<textarea value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></label><button className="primary">Agendar retorno</button></form><article className="panel"><div className="panel-title"><h2>Meus retornos</h2><span>{visible.length}</span></div><div className="agenda-list">{visible.map(a=><div className={`agenda-item ${a.status==='Concluído'?'done':''}`} key={a.id}><div className="agenda-date"><b>{new Date(a.data+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</b><span>{a.hora}</span></div><div><b>{name(a.revendedorId)}</b><small>{a.observacao||'Sem observação'} · {a.responsavel}</small></div><button className="small-action" onClick={()=>onUpdate(a.id,{status:a.status==='Concluído'?'Pendente':'Concluído'})}>{a.status==='Concluído'?<MessageCircle size={16}/>:<CheckCircle2 size={16}/>} {a.status}</button></div>)}{!visible.length&&<div className="empty">Nenhum retorno agendado.</div>}</div></article></div></section>
}
