import React,{useMemo,useState}from'react';
import{Megaphone,Plus,Send,Users,Trash2,BarChart3,Eye}from'lucide-react';
import{matchesCampaign}from'../services/intelligence';
const groups=['Recuperação','Cobre a Ouro','VIP','Todos'];
export default function Campaigns({campaigns=[],revendedores=[],onAdd,onDelete,onRun}){
 const[name,setName]=useState(''),[group,setGroup]=useState('Todos'),[message,setMessage]=useState('Olá, {nome}! Temos novidades para você neste ciclo. Posso te apresentar?'),[preview,setPreview]=useState(false);
 const audience=useMemo(()=>revendedores.filter(r=>matchesCampaign(r,group)&&r.telefone),[revendedores,group]);
 const sample=audience[0];
 const rendered=sample?message.replaceAll('{nome}',sample.nome||'').replaceAll('{cidade}',sample.cidade||'').replaceAll('{nivel}',sample.nivel||''):message;
 const submit=e=>{e.preventDefault();if(!name.trim()||!message.trim())return;onAdd({id:crypto.randomUUID(),name:name.trim(),group,message:message.trim(),createdAt:new Date().toISOString(),status:'Rascunho',sent:0,replies:0,conversions:0});setName('')};
 const totals=campaigns.reduce((a,c)=>({sent:a.sent+(c.sent||0),replies:a.replies+(c.replies||0),conversions:a.conversions+(c.conversions||0)}),{sent:0,replies:0,conversions:0});
 return <div className="module-page"><div className="campaign-kpis"><div><Send/><b>{totals.sent}</b><span>Envios preparados</span></div><div><Users/><b>{totals.replies}</b><span>Respostas registradas</span></div><div><BarChart3/><b>{totals.conversions}</b><span>Conversões atribuídas</span></div></div><div className="campaign-grid"><form className="panel form-panel" onSubmit={submit}><div className="panel-title"><div><h2>Nova campanha</h2><span>Crie mensagens por carteira.</span></div><Megaphone/></div><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Reativação do ciclo"/></label><label>Público<select value={group} onChange={e=>setGroup(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label>Mensagem<textarea value={message} onChange={e=>setMessage(e.target.value)} rows="7"/></label><div className="template-help"><b>Variáveis disponíveis:</b> {'{nome}'}, {'{cidade}'}, {'{nivel}'}</div><div className="audience-preview"><Users size={18}/><b>{audience.length}</b> revendedores com telefone válido</div><button type="button" className="secondary-btn" onClick={()=>setPreview(v=>!v)}><Eye size={17}/>{preview?'Ocultar prévia':'Ver prévia'}</button>{preview&&<div className="message-preview"><small>Prévia para {sample?.nome||'um contato'}</small><p>{rendered}</p></div>}<button className="primary" type="submit"><Plus size={17}/>Salvar campanha</button></form><section className="panel"><div className="panel-title"><div><h2>Campanhas salvas</h2><span>Fila individual via WhatsApp.</span></div></div><div className="campaign-list">{campaigns.length===0?<div className="empty">Nenhuma campanha criada.</div>:campaigns.map(c=>{const qty=revendedores.filter(r=>matchesCampaign(r,c.group)&&r.telefone).length;return <article className="campaign-card" key={c.id}><div className="campaign-card-head"><div><strong>{c.name}</strong><small>{c.group} · {qty} contatos</small></div><span className="pill">{c.status||'Rascunho'}</span></div><p>{c.message}</p><div className="campaign-metrics"><span><b>{c.sent||0}</b> preparados</span><span><b>{c.replies||0}</b> respostas</span><span><b>{c.conversions||0}</b> conversões</span></div><div className="campaign-actions"><button className="small-action" onClick={()=>onRun(c)}><Send size={15}/>Abrir próximo contato</button><button className="danger-btn" onClick={()=>onDelete(c.id)}><Trash2 size={15}/></button></div></article>})}</div></section></div></div>}
