import React,{useMemo,useState}from'react';
import{Shuffle,Camera,Save,RotateCcw,Lock,Coins,Star,Search}from'lucide-react';
import AvatarPreview from'./AvatarPreview';
import{characters,skinTones,hairColors,hairStyles,faceShapes,eyeStyles,brows,facialHair,outfits,accessories,shoes,scenes,poses,defaultAvatar}from'../data/avatarOptions';
const tabs=['Personagem','Rosto','Cabelo','Roupas','Acessórios','Calçados','Cenário'];
const swatch=(value,label)=>({value,label});
export default function Closet({initialAvatar,onSave,coins=420}){
 const[tab,setTab]=useState('Personagem'),[avatar,setAvatar]=useState({...defaultAvatar,...initialAvatar}),[query,setQuery]=useState('');
 const update=(k,v)=>setAvatar(a=>({...a,[k]:v})); const pick=a=>a[Math.floor(Math.random()*a.length)];
 const randomize=()=>setAvatar({...defaultAvatar,character:pick(characters).id,skin:pick(skinTones),hairColor:pick(hairColors),hairStyle:pick(hairStyles),faceShape:pick(faceShapes),eyeStyle:pick(eyeStyles),brow:pick(brows),facialHair:pick(facialHair),outfit:pick(outfits),accessory:pick(accessories),shoes:pick(shoes),scene:pick(scenes),pose:pick(poses),expressionIndex:Math.floor(Math.random()*6)});
 const filtered=(items)=>items.filter(item=>String(typeof item==='string'?item:item.label).toLowerCase().includes(query.toLowerCase()));
 const cards=(items,key,lockedAfter=999,mode='avatar')=> <div className="option-grid">{filtered(items).map((item,i)=>{const value=typeof item==='string'?item:item.id,label=typeof item==='string'?item:item.label,locked=i>=lockedAfter;return <button type="button" key={value} disabled={locked} className={`option-card ${avatar[key]===value?'active':''}`} onClick={()=>update(key,value)}>{locked&&<span className="locked"><Lock size={13}/>80</span>}<span className={`option-preview ${mode==='text'?'text-preview':''}`}>{mode==='avatar'?<AvatarPreview compact avatar={{...avatar,[key]:value}}/>:<b>{label.slice(0,2).toUpperCase()}</b>}</span><strong>{label}</strong></button>})}</div>;
 const progress=useMemo(()=>Math.min(100,Math.round((Object.values(avatar).filter(Boolean).length/14)*100)),[avatar]);
 return <section className="closet-page"><div className="closet-toolbar"><div><span className="eyebrow">Avatar Studio</span><h2>Seu personagem, seu estilo</h2><p>Crie um visual exclusivo para aparecer no perfil, ranking e painel da equipe.</p></div><div className="closet-tools"><span className="coin-pill"><Coins size={17}/>{coins} moedas</span><button className="primary" onClick={()=>onSave?.(avatar)}><Save size={18}/>Salvar no perfil</button></div></div>
 <div className="closet-grid"><div className="preview-card"><div className="avatar-progress"><span>Personalização</span><b>{progress}%</b><progress value={progress} max="100"/></div><div className={`preview-stage scene-${String(avatar.scene).replaceAll(' ','-').toLowerCase()}`}><div className="stage-glow"/><AvatarPreview avatar={avatar}/><span className="avatar-nameplate">{characters.find(c=>c.id===avatar.character)?.label||'Meu avatar'}</span></div><div className="preview-actions"><button onClick={randomize}><Shuffle size={18}/>Aleatório</button><button onClick={()=>window.print()}><Camera size={18}/>Foto</button><button onClick={()=>setAvatar(defaultAvatar)}><RotateCcw size={18}/>Redefinir</button></div><div className="pose-row"><span>Pose</span>{poses.map(p=><button className={avatar.pose===p?'active':''} onClick={()=>update('pose',p)} key={p}>{p}</button>)}</div><div className="closet-tip"><Star size={18}/><div><b>Dica</b><p>Ganhe moedas ao registrar atendimentos e conversões para desbloquear itens premium.</p></div></div></div>
 <div className="editor-card"><div className="tabs">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setQuery('')}}>{t}</button>)}</div><label className="closet-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar em ${tab.toLowerCase()}...`}/></label>
 {tab==='Personagem'&&<><h3>Personagem</h3>{cards(characters,'character')}<h3>Tom de pele</h3><div className="swatches">{skinTones.map(c=><button aria-label="Tom de pele" key={c} className={avatar.skin===c?'active':''} style={{background:c}} onClick={()=>update('skin',c)}/>)}</div></>}
 {tab==='Rosto'&&<><h3>Formato do rosto</h3>{cards(faceShapes,'faceShape',999,'text')}<h3>Olhos</h3>{cards(eyeStyles,'eyeStyle',999,'text')}<h3>Sobrancelhas</h3>{cards(brows,'brow',999,'text')}<h3>Barba e bigode</h3>{cards(facialHair,'facialHair',999,'text')}<h3>Expressão</h3><div className="expression-options">{['😀','😄','😊','😍','😎','😤'].map((e,i)=><button key={e} className={avatar.expressionIndex===i?'active':''} onClick={()=>update('expressionIndex',i)}>{e}</button>)}</div></>}
 {tab==='Cabelo'&&<><h3>Estilo</h3>{cards(hairStyles,'hairStyle',999,'text')}<h3>Cor</h3><div className="swatches">{hairColors.map(c=><button aria-label="Cor do cabelo" key={c} className={avatar.hairColor===c?'active':''} style={{background:c}} onClick={()=>update('hairColor',c)}/>)}</div></>}
 {tab==='Roupas'&&<><h3>Roupas</h3>{cards(outfits,'outfit',12)}</>}{tab==='Acessórios'&&<><h3>Acessórios</h3>{cards(accessories,'accessory',12)}</>}{tab==='Calçados'&&<><h3>Calçados</h3>{cards(shoes,'shoes')}</>}{tab==='Cenário'&&<><h3>Cenários</h3>{cards(scenes,'scene',999,'text')}</>}
 </div></div></section>
}
