import React,{useMemo}from'react';
import{Users,MessageCircle,RotateCcw,Trophy,TrendingUp,Target,Clock3,CalendarDays}from'lucide-react';
const pct=(a,b)=>b?Math.round(a/b*100):0;
export default function Dashboard({revendedores,history=[],agenda=[]}){
 const stats=useMemo(()=>{const total=revendedores.length,vips=revendedores.filter(r=>['Platina','Rubi','Esmeralda','Diamante'].includes(r.nivel)).length,recuperacao=revendedores.filter(r=>['I6','Cessados','Intenções'].includes(r.base)).length,convertidos=revendedores.filter(r=>r.status==='Convertido').length,emContato=revendedores.filter(r=>['Em contato','Retorno'].includes(r.status)).length,pendentes=revendedores.filter(r=>r.status==='Pendente').length,atrasados=agenda.filter(a=>a.status!=='Concluído'&&new Date(`${a.data}T${a.hora||'23:59'}`)<new Date()).length,hoje=agenda.filter(a=>a.data===new Date().toISOString().slice(0,10)&&a.status!=='Concluído').length;return{total,vips,recuperacao,convertidos,emContato,pendentes,atrasados,hoje,rate:pct(convertidos,total)}},[revendedores,agenda]);
 const cards=[['Revendedores',stats.total,Users,'Carteira total'],['Em atendimento',stats.emContato,MessageCircle,'Contatos em andamento'],['Recuperação',stats.recuperacao,RotateCcw,'I6, cessados e intenções'],['VIP',stats.vips,Trophy,'Platina a diamante'],['Conversões',stats.convertidos,TrendingUp,`${stats.rate}% da carteira`],['Retornos hoje',stats.hoje,CalendarDays,`${stats.atrasados} atrasados`]];
 const byBase=Object.entries(revendedores.reduce((a,r)=>{a[r.base]=(a[r.base]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]);
 const byLevel=Object.entries(revendedores.reduce((a,r)=>{a[r.nivel]=(a[r.nivel]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,6);
 const recent=[...history].sort((a,b)=>String(b.data).localeCompare(String(a.data))).slice(0,5);
 return <section className="module-page dashboard-premium">
  <div className="hero-strip"><div><span>Visão executiva</span><h2>Bom trabalho! Sua operação está organizada.</h2><p>Acompanhe carteira, conversões, retornos e prioridades em um único lugar.</p></div><div className="hero-score"><Target/><b>{stats.rate}%</b><small>taxa de conversão</small></div></div>
  <div className="kpi-grid premium-kpis">{cards.map(([label,value,Icon,help])=><article className="kpi-card premium" key={label}><span><Icon size={22}/></span><div><small>{label}</small><strong>{value}</strong><em>{help}</em></div></article>)}</div>
  <div className="dashboard-grid premium-grid">
   <article className="panel"><div className="panel-title"><div><small>Carteira</small><h2>Distribuição por base</h2></div><span>{stats.total} contatos</span></div><div className="bar-list">{byBase.map(([name,value])=><div key={name}><div><b>{name}</b><span>{value}</span></div><progress value={value} max={Math.max(stats.total,1)}/></div>)}</div></article>
   <article className="panel"><div className="panel-title"><div><small>Funil</small><h2>Etapas atuais</h2></div><span>Atualizado agora</span></div><div className="funnel-visual"><div><i style={{width:`${pct(stats.pendentes,stats.total)}%`}}/><b>Pendentes</b><span>{stats.pendentes}</span></div><div><i style={{width:`${pct(stats.emContato,stats.total)}%`}}/><b>Em contato</b><span>{stats.emContato}</span></div><div><i style={{width:`${pct(stats.convertidos,stats.total)}%`}}/><b>Convertidos</b><span>{stats.convertidos}</span></div></div></article>
   <article className="panel"><div className="panel-title"><div><small>Segmentação</small><h2>Níveis da carteira</h2></div><span>Top 6</span></div><div className="level-cloud">{byLevel.map(([name,value])=><div key={name}><b>{name}</b><span>{value}</span></div>)}</div></article>
   <article className="panel"><div className="panel-title"><div><small>Atividade</small><h2>Últimos atendimentos</h2></div><Clock3 size={18}/></div><div className="activity-feed">{recent.length===0?<div className="empty">Nenhum atendimento registrado.</div>:recent.map(item=><div key={item.id}><i/><div><b>{item.resultado}</b><span>{item.usuario} · {item.canal}</span></div><small>{new Date(item.data).toLocaleDateString('pt-BR')}</small></div>)}</div></article>
  </div>
 </section>
}
