import React, {useRef, useState} from 'react';
import { UploadCloud, FileSpreadsheet, CheckCircle2 } from 'lucide-react';
import * as XLSX from 'xlsx';

const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const pick=(row,names)=>{const key=Object.keys(row).find(k=>names.some(n=>norm(k).includes(n))); return key?row[key]:''};
function detectBase(sheetName,row){const t=norm(sheetName+' '+Object.keys(row).join(' ')); if(t.includes('intenc'))return 'Intenções'; if(t.includes('cess'))return 'Cessados'; if(t.includes('i6'))return 'I6'; if(t.includes('vip'))return 'VIP'; return 'Atividade'}
function detectLevel(value,base){const t=norm(value); const names=['cobre','bronze','prata','ouro','platina','rubi','esmeralda','diamante']; const f=names.find(x=>t.includes(x)); return f?f[0].toUpperCase()+f.slice(1):(base==='VIP'?'Platina':'Cobre')}
export default function Importer({onImport,imports}){
 const input=useRef(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const process=async files=>{setBusy(true);setMessage('');let all=[];let summary=[]; try{for(const file of files){const data=await file.arrayBuffer();const wb=XLSX.read(data);let count=0;wb.SheetNames.forEach(sheetName=>{const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{defval:''});rows.forEach((row,i)=>{const nome=pick(row,['nome','revendedor','razao']); if(!String(nome).trim())return; const base=detectBase(sheetName,row); const rawLevel=pick(row,['nivel','segmento','faixa','vip']); const cycles=pick(row,['ciclo','inativ']); all.push({id:`imp-${Date.now()}-${all.length}`,codigo:String(pick(row,['codigo','cod rev','id'])),nome:String(nome).trim(),telefone:String(pick(row,['telefone','celular','whatsapp'])).replace(/\D/g,''),cidade:String(pick(row,['cidade','municipio'])),nivel:detectLevel(rawLevel,base),base,atividade:base==='I6'?'Inativo 6':base==='Cessados'?'Cessado 7':base==='Intenções'?'Intenção':String(cycles||'Ativo 1'),status:'Pendente',responsavel:'—'});count++})});summary.push({name:file.name,count,date:new Date().toISOString()})}onImport(all,summary);setMessage(`${all.length} registros processados em ${summary.length} arquivo(s).`)}catch(e){setMessage('Não foi possível ler a planilha: '+e.message)}finally{setBusy(false)}};
 return <section className="module-page"><div className="import-grid"><article className="upload-card" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();process([...e.dataTransfer.files])}}><UploadCloud size={44}/><h2>Importar bases</h2><p>Arraste as planilhas aqui ou selecione arquivos XLSX/XLS.</p><button className="primary" onClick={()=>input.current.click()} disabled={busy}>{busy?'Processando...':'Selecionar planilhas'}</button><input ref={input} hidden type="file" multiple accept=".xlsx,.xls" onChange={e=>process([...e.target.files])}/>{message&&<div className="import-message"><CheckCircle2 size={18}/>{message}</div>}</article><article className="panel"><div className="panel-title"><h2>Reconhecimento automático</h2></div><ul className="feature-list"><li>Atividade e níveis Cobre a Ouro</li><li>VIP: Platina, Rubi, Esmeralda e Diamante</li><li>I6, Cessados e Intenções</li><li>Consolidação por código, telefone ou nome</li></ul></article></div><article className="panel import-history"><div className="panel-title"><h2>Histórico de importações</h2><span>{imports.length}</span></div>{imports.length?imports.map((i,idx)=><div className="import-row" key={idx}><FileSpreadsheet size={20}/><div><b>{i.name}</b><small>{new Date(i.date).toLocaleString('pt-BR')}</small></div><strong>{i.count} registros</strong></div>):<div className="empty">Nenhuma importação realizada nesta versão.</div>}</article></section>
}
