import React,{useMemo,useState}from'react';
import{Download,FileSpreadsheet,TrendingUp,Users,CheckCircle2,Clock3,Phone,MessageCircle}from'lucide-react';
const csv=(rows)=>rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n');
const save=(name,text)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
export default function Reports({revendedores=[],history=[],agenda=[]}){
 const[period,setPeriod]=useState('Todos');
 const filteredHistory=useMemo(()=>{if(period==='Todos')return history;const days=Number(period);const cutoff=Date.now()-days*86400000;return history.filter(h=>new Date(h.data).getTime()>=cutoff)},[history,period]);
 const stats=useMemo(()=>({total:revendedores.length,converted:revendedores.filter(r=>r.status==='Convertido').length,contacts:filteredHistory.length,calls:filteredHistory.filter(h=>h.canal==='Ligação').length,whats:filteredHistory.filter(h=>h.canal==='WhatsApp').length,overdue:agenda.filter(a=>a.status!=='Concluído'&&new Date(`${a.data}T${a.hora||'23:59'}`)<new Date()).length}),[revendedores,filteredHistory,agenda]);
 const byBase=useMemo(()=>Object.entries(revendedores.reduce((a,r)=>(a[r.base||'Sem base']=(a[r.base||'Sem base']||0)+1,a),{})).sort((a,b)=>b[1]-a[1]),[revendedores]);
 const byUser=useMemo(()=>Object.entries(filteredHistory.reduce((a,h)=>{const k=h.usuario||'Sem usuário';a[k]??={contacts:0,conversions:0};a[k].contacts++;if(h.resultado==='Convertido')a[k].conversions++;return a},{})).sort((a,b)=>b[1].conversions-a[1].conversions||b[1].contacts-a[1].contacts),[filteredHistory]);
 const exportWallet=()=>save('carteira-randerscrm.csv',csv([['Código','Nome','Telefone','Cidade','Nível','Base','Atividade','Status'],...revendedores.map(r=>[r.codigo,r.nome,r.telefone,r.cidade,r.nivel,r.base,r.atividade,r.status])]));
 const exportHistory=()=>save('historico-randerscrm.csv',csv([['Data','Revendedor','Usuário','Canal','Resultado','Observação'],...filteredHistory.map(h=>[h.data,revendedores.find(r=>r.id===h.revendedorId)?.nome||'',h.usuario,h.canal,h.resultado,h.observacao])]));
 return <div className="module-page"><div className="report-toolbar"><div><b>Período dos atendimentos</b><small>Os dados da carteira permanecem atuais.</small></div><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Todos</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option></select></div><div className="report-kpis report-kpis-six"><div className="report-kpi"><Users/><div><b>{stats.total}</b><span>Revendedores</span></div></div><div className="report-kpi"><CheckCircle2/><div><b>{stats.converted}</b><span>Convertidos</span></div></div><div className="report-kpi"><TrendingUp/><div><b>{stats.contacts}</b><span>Atendimentos</span></div></div><div className="report-kpi"><Phone/><div><b>{stats.calls}</b><span>Ligações</span></div></div><div className="report-kpi"><MessageCircle/><div><b>{stats.whats}</b><span>WhatsApps</span></div></div><div className="report-kpi"><Clock3/><div><b>{stats.overdue}</b><span>Retornos atrasados</span></div></div></div><div className="report-grid"><section className="panel"><div className="panel-title"><div><h2>Distribuição por base</h2><span>Resumo da carteira atual.</span></div></div><div className="bar-list">{byBase.map(([label,value])=><div key={label}><div><b>{label}</b><span>{value}</span></div><progress max={Math.max(...byBase.map(([,v])=>v),1)} value={value}/></div>)}</div></section><section className="panel"><div className="panel-title"><div><h2>Desempenho por colaborador</h2><span>Atendimentos e conversões no período.</span></div></div><div className="performance-list">{byUser.length===0?<div className="empty">Sem atendimentos no período.</div>:byUser.map(([name,s])=><div key={name}><div><b>{name}</b><small>{s.contacts} atendimentos</small></div><span>{s.conversions} conversões</span></div>)}</div></section><section className="panel export-panel"><div className="panel-title"><div><h2>Exportações</h2><span>Arquivos compatíveis com Excel.</span></div><FileSpreadsheet/></div><div className="export-actions"><button className="primary" onClick={exportWallet}><Download size={17}/>Exportar carteira</button><button className="secondary-btn" onClick={exportHistory}><Download size={17}/>Exportar histórico</button></div><p className="muted-note">Os relatórios respeitam a carteira visível do usuário conectado.</p></section></div></div>}
