import React,{useMemo,useState}from'react';
import{Search,MessageCircle,Filter,Clock3,Star}from'lucide-react';
const levels=['Todos','Cobre','Bronze','Prata','Ouro','Platina','Rubi','Esmeralda','Diamante'];
const bases=['Todas','Atividade','VIP','I6','Cessados','Intenções'];
export default function Wallet({revendedores,onUpdate,onTimeline}){
 const[q,setQ]=useState(''),[level,setLevel]=useState('Todos'),[base,setBase]=useState('Todas'),[priority,setPriority]=useState('Todas'),[sort,setSort]=useState('score');
 const rows=useMemo(()=>revendedores.filter(r=>{const hay=`${r.nome} ${r.codigo} ${r.telefone} ${r.cidade}`.toLowerCase();return hay.includes(q.toLowerCase())&&(level==='Todos'||r.nivel===level)&&(base==='Todas'||r.base===base)&&(priority==='Todas'||r.prioridade===priority)}).sort((a,b)=>sort==='score'?(b.score||0)-(a.score||0):sort==='nome'?String(a.nome).localeCompare(String(b.nome)):(String(a.cidade||'').localeCompare(String(b.cidade||'')))),[revendedores,q,level,base,priority,sort]);
 const openWhats=r=>{const n=String(r.telefone||'').replace(/\D/g,'');if(n.length<10)return alert('Telefone inválido.');const phone=n.startsWith('55')?n:`55${n}`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(`Olá, ${r.nome}! Tudo bem? Aqui é da equipe de relacionamento.`)}`,'_blank')};
 return <section className="module-page"><div className="toolbar"><label className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar nome, código, telefone ou cidade"/></label><label><Filter size={17}/><select value={level} onChange={e=>setLevel(e.target.value)}>{levels.map(x=><option key={x}>{x}</option>)}</select></label><label><select value={base} onChange={e=>setBase(e.target.value)}>{bases.map(x=><option key={x}>{x}</option>)}</select></label><label><select value={priority} onChange={e=>setPriority(e.target.value)}><option>Todas</option><option>Alta</option><option>Média</option><option>Baixa</option></select></label><label><select value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Maior prioridade</option><option value="nome">Nome</option><option value="cidade">Cidade</option></select></label></div><div className="smart-summary"><Star size={18}/><b>{rows.filter(r=>r.prioridade==='Alta').length}</b> contatos de alta prioridade na seleção atual.</div><div className="table-wrap"><table><thead><tr><th>Revendedor</th><th>Cidade</th><th>Nível</th><th>Base</th><th>Prioridade</th><th>Próxima ação</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><button className="link-button" onClick={()=>onTimeline(r)}>{r.nome}</button><small>{r.codigo} · {r.telefone}</small></td><td>{r.cidade}</td><td><span className="pill">{r.nivel}</span></td><td>{r.base}</td><td><div className="priority-cell"><span className={`priority priority-${(r.prioridade||'Média').toLowerCase().replace('é','e')}`}>{r.prioridade||'Média'}</span><small>{r.score||0}/100</small></div></td><td><b className="next-action">{r.nextAction}</b><small>{r.recommendedChannel} · {r.motivoPrioridade}</small></td><td><select value={r.status} onChange={e=>onUpdate(r.id,{status:e.target.value})}><option>Pendente</option><option>Em contato</option><option>Retorno</option><option>Convertido</option><option>Não converteu</option></select></td><td><div className="row-actions"><button className="small-action" onClick={()=>openWhats(r)}><MessageCircle size={16}/>WhatsApp</button><button className="small-action ghost" onClick={()=>onTimeline(r)}><Clock3 size={16}/>Timeline</button></div></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty">Nenhum revendedor encontrado.</div>}</div></section>}
